### ISSUE TITLE
Backend - Add indentation config to Project model, and use in YAML locale file generation.

### ISSUE THREAD

**Issue by richardolsson** [zetkin/translators-interface#11]
## Description
The different Zetkin projects do not use consistent indentation within YAML locale files. Some use 2 spaces, and some use 4. In order to keep the "git diff" as small as possible, we want to be able to configure the indentation used in a project so that when the new YAML files are generated they have the same indentation that was already used in the project.

### Files that you will work with
* [backend/translations/models/project.py](https://github.com/zetkin/translators-interface/blob/master/backend/translations/models/project.py)
* [backend/translations/utils/generate_locale_files.py](https://github.com/zetkin/translators-interface/blob/master/backend/translations/utils/generate_locale_files.py)
  * [backend/translations/utils/tests/test_generate_locale_files.py](https://github.com/zetkin/translators-interface/blob/master/backend/translations/utils/tests/test_generate_locale_files.py) 

### Set up the environment
1. Create the local dev environment following the instructions in the README. You will need a superuser to access Django Admin
2. Go to the Django Admin at `localhost:8000/admin` and sign in with the superuser
3. Pick a project from https://github.com/zetkin and find the locale files within it.
4. Create Language objects in the Django Admin for each language in the project.

From here you can create a Project object. Once you make the changes, you should see the field for the indentation spaces used in the form for Project objects.

### Validating your work
To check your work is correct, this is what is expected:
1. Set up a project using the steps above. Set any value of indentation you wish.
2. Click the checkbox for your project and from the actions dropdown select: "Export locale files"
3. Open the downloaded files and check the indentation is correct.

## Requirements
* There should be an integer field on the Project model that representations the number of spaces that are used for indentation.
  * The default value should be 4.
* When locale files are generated, the indentation should be correct for the project.
* There should be a small test case that this functionality works as expected.

**Comment by djbusstop** [comment]
Implemented and released.
